# Generated by Django 5.2.4 on 2025-08-04 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dpi', models.CharField(max_length=100)),
                ('dpi_imagen', models.ImageField(blank=True, null=True, upload_to='ciudadanos/dpi/')),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_colaborador', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('departamento_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.departamentogestion')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('departamento_gestion', models.CharField(max_length=100)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Ingresada'), (2, 'En proceso'), (3, 'Reingreso'), (4, 'Autorizada'), (5, 'Finalizada'), (6, 'Cancelada')], default=1)),
                ('importante', models.BooleanField(default=False)),
                ('media', models.BooleanField(default=False)),
                ('urgente', models.BooleanField(default=False)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ciudadano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MuniColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_muni_colaborador', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('departamento_gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.departamentogestion')),
            ],
        ),
        migrations.AddField(
            model_name='departamentogestion',
            name='MuniColaborador',
            field=models.ManyToManyField(blank=True, to='tasks.municolaborador'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
