# Generated by Django 5.2.4 on 2025-08-13 19:31

import django.core.validators
import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentogestion',
            name='MuniColaborador',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='title1',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='Estado_civil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Soltero/a'), (2, 'casado/a'), (3, 'Divorciado/a'), (4, 'viudo/a'), (5, 'union libre')], default=1),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=1, max_length=1, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='correo_colaborador',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='dpi_colaborador',
            field=models.CharField(default=1, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefono_colaborador',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener un formato válido.', regex='^\\+?1?\\d{8}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamentogestion',
            name='Colaborador_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.colaborador'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='numero_gestion',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dpi',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_dpi', message='Ingrese un DPI válido de 13 dígitos.', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener un formato válido.', regex='^\\+?1?\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='departamentogestion',
            name='nombre_departamento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ingresada'), (2, 'En proceso'), (3, 'Reingreso'), (4, 'Autorizada'), (5, 'Finalizada'), (6, 'Cancelada')], default=1),
        ),
        migrations.CreateModel(
            name='Solicitud_gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(default=tasks.models.generar_numero, max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Ingresada'), (2, 'En proceso'), (3, 'Reingreso'), (4, 'Autorizada'), (5, 'Finalizada'), (6, 'Cancelada')], default=1)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ciudadano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MuniColaborador',
        ),
    ]
