# Generated by Django 5.2.4 on 2025-08-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_departamentogestion_municolaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='departamento_gestion',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alcaldía Municipal'), (2, 'Departamento de Finanzas'), (3, 'Secretaría General'), (4, 'Recepción'), (5, 'DMP'), (6, 'DMM'), (7, 'OMNAP'), (8, 'RECURSOS HUMANOS'), (9, 'CONTABILIDAD'), (10, 'COMPRAS')], default=1),
        ),
        migrations.AlterField(
            model_name='departamentogestion',
            name='nombre_departamento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Alcaldía Municipal'), (2, 'Departamento de Finanzas'), (3, 'Secretaría General'), (4, 'Recepción'), (5, 'DMP'), (6, 'DMM'), (7, 'OMNAP'), (8, 'RECURSOS HUMANOS'), (9, 'CONTABILIDAD'), (10, 'COMPRAS')], default=1),
        ),
    ]
