# Generated by Django 5.2.4 on 2025-08-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_colaborador_departamento_gestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='clave',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='clave_colaborador',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
