# Generated by Django 5.2.4 on 2025-08-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_colaborador_clave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='departamento_gestion',
            field=models.PositiveSmallIntegerField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default=1),
        ),
        migrations.AlterField(
            model_name='departamentogestion',
            name='nombre_departamento',
            field=models.PositiveSmallIntegerField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default=1),
        ),
    ]
