# Generated by Django 5.2.4 on 2025-08-18 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_colaborador_departamento_gestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='clave_colaborador',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='departamento_gestion',
            field=models.PositiveSmallIntegerField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default=1),
        ),
    ]
