# Generated by Django 5.2.4 on 2025-08-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_colaborador_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='numero_gestion',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='Estado_civil',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Soltero/a'), (2, 'casado/a'), (3, 'Divorciado/a'), (4, 'viudo/a'), (5, 'union libre')], default=1),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default=1, max_length=1, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='departamento_gestion',
            field=models.CharField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default='AM', max_length=10),
        ),
        migrations.AlterField(
            model_name='departamentogestion',
            name='nombre_departamento',
            field=models.CharField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default='AM', max_length=10),
        ),
    ]
