# Generated by Django 5.2.4 on 2025-08-18 21:20

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_gestion_numero_gestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='clave_colaborador',
            field=models.CharField(default=tasks.models.generar_clave, max_length=20, unique=True),
        ),
    ]
