# Generated by Django 5.2.4 on 2025-08-18 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_colaborador_clave_colaborador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='clave_colaborador',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='correo_colaborador',
            field=models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_email', message='Ingrese una dirección de correo electrónico válida.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
