# Generated by Django 5.2.4 on 2025-08-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_colaborador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion',
            name='departamento_gestion',
            field=models.CharField(choices=[('AM', 'Alcaldía Municipal'), ('DAFIM', 'Departamento de Finanzas'), ('SG', 'Secretaría General'), ('RC', 'Recepción'), ('DMP', 'DMP'), ('DMM', 'DMM'), ('OMNAP', 'OMNAP'), ('RH', 'RECURSOS HUMANOS'), ('CT', 'CONTABILIDAD'), ('CP', 'COMPRAS')], default='AM', max_length=10),
        ),
    ]
