# Generated by Django 5.2.4 on 2025-08-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_solicitud_gestion_tipo_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud_gestion',
            name='Tipo_solicitud',
            field=models.CharField(choices=[(1, 'Solicitud de Agua'), (2, 'Solicitud Drenaje'), (3, 'Solicitud de Alumbrado'), (4, 'Solicitud de Ayuda Social'), (5, 'Solicitud de Mantenimiento'), (6, 'Solicitud de Certificación'), (7, 'Solicitud de Permiso'), (8, 'Solicitud de Información'), (9, 'Solicitud de Queja'), (10, 'Solicitud de carta de Residencia'), (11, 'Solicitud de procesos Jurídicos'), (12, 'Solicitud de Certificación de Nichos'), (13, 'Solicitud de Certificación de Propiedad'), (14, 'Solicitud de Donaciones'), (15, 'Solicitud de Licencia de Funcionamiento'), (16, 'Solicitud de Limpieza de calles'), (17, 'Solicitud de Mantenimiento de Agua Xepacay'), (18, 'Solicitud de Mantenimiento de Parques'), (19, 'Solicitud de Mantenimiento de Cementerio'), (20, 'Solicitud de Donaciones de Arboles'), (21, 'Solicitud de Actividades Culturales'), (22, 'Solicitud de Actividades Deportivas'), (23, 'Solicitud de Actividades Recreativas'), (24, 'Solicitud de Actividades Educativas'), (25, 'Solicitud de Actividades Sociales'), (26, 'Solicitud de Actividades Económicas'), (27, 'Solicitud de Actividades Ambientales'), (28, 'Solicitud de Actividades de Salud'), (29, 'Solicitud de Actividades de Seguridad'), (30, 'Solicitud de Actividades de Infraestructura'), (31, 'Solicitud de Actividades de Actividades de Ferias'), (32, 'Solicitud de Control Fontanería'), (33, 'Solicitud de Alquiler de Espacios Públicos'), (34, 'Solicitud de Alquiler de Salones'), (35, 'Otros')], default=1, max_length=10),
        ),
    ]
